Default: &defaults
  database: english219.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: english219_test.sqlite3
  <<: *defaults

Staging:
  database: english219_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: english219_production.sqlite3
  poolsize: 100
  <<: *defaults
